default_context:
  _pegasus_version: '2023.3'
  author_name: Maurice
  ci: github_actions
  css_framework: bootstrap
  css_theme: bootstrap-material
  database: postgres
  deploy_platform: digital_ocean_app_platform
  description: Dynamic Api generator
  domain_name: localhost:8000
  email: maurice.schilpp.beyond@gmail.com
  enable_google_login: y
  enable_twitter_login: y
  front_end_framework: react
  post_process: y
  project_name: API Gate
  project_slug: api_gate
  stripe_payment_mode: both
  subscription_billing_model: default
  use_2fa: y
  use_api_keys: y
  use_cloud_media_storage: y
  use_debug_toolbar: y
  use_docker: y
  use_examples: y
  use_impersonation: y
  use_sentry: y
  use_subscriptions: y
  use_teams: y
  use_translations: y
  use_wagtail: n
