/* tslint:disable */
/* eslint-disable */
/**
 * API Gate
 * Dynamic Api generator
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Price } from './Price';
import {
    PriceFromJSON,
    PriceFromJSONTyped,
    PriceToJSON,
} from './Price';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
} from './Product';
import type { ProductMetadata } from './ProductMetadata';
import {
    ProductMetadataFromJSON,
    ProductMetadataFromJSONTyped,
    ProductMetadataToJSON,
} from './ProductMetadata';

/**
 * 
 * @export
 * @interface ProductWithMetadata
 */
export interface ProductWithMetadata {
    /**
     * 
     * @type {Product}
     * @memberof ProductWithMetadata
     */
    product: Product;
    /**
     * 
     * @type {ProductMetadata}
     * @memberof ProductWithMetadata
     */
    metadata: ProductMetadata;
    /**
     * 
     * @type {{ [key: string]: Price; }}
     * @memberof ProductWithMetadata
     */
    activePrices: { [key: string]: Price; };
}

/**
 * Check if a given object implements the ProductWithMetadata interface.
 */
export function instanceOfProductWithMetadata(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "product" in value;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "activePrices" in value;

    return isInstance;
}

export function ProductWithMetadataFromJSON(json: any): ProductWithMetadata {
    return ProductWithMetadataFromJSONTyped(json, false);
}

export function ProductWithMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductWithMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'product': ProductFromJSON(json['product']),
        'metadata': ProductMetadataFromJSON(json['metadata']),
        'activePrices': (mapValues(json['active_prices'], PriceFromJSON)),
    };
}

export function ProductWithMetadataToJSON(value?: ProductWithMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'product': ProductToJSON(value.product),
        'metadata': ProductMetadataToJSON(value.metadata),
        'active_prices': (mapValues(value.activePrices, PriceToJSON)),
    };
}

